### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by jesstracy** [jesstracy/gapi#2]

**Comment by chrisevett** [comment]
@jesstracy going to tackle this next. I've been using a framework called http://onsi.github.io/ginkgo/ that's been treating me pretty well so I'm going to keep on with that. Also, this guy should help us test the http routes etc http://agouti.org/

**Comment by chrisevett** [comment]
@jesstracy 

Ok I think I have a good way to improve our encapsulation situation so we dont hit our database when we run tests. 

Check out this commit https://github.com/chrisevett/gapi/commit/d5272becb048e9d96229d3e1c92a9f56aee79843

Forget the game folder 

Basically I tried to abstract the data layer so it gets inferred by the router using gin middleware. Since we create routes as part of the test we can assign it a fake middleware that will return fake data during testing. 

I still don't have a good way to test /actual/ routes with a unit test, we will probably want to do that with an integration test suite that actually involves a real testing database.

Let me know what you think about my :b:utt and if you like what you see i will change the rest of the methods to follow that pattern.

**Comment by chrisevett** [comment]
I get to close one HELL YEAH resolved by #20
