### ISSUE TITLE
domain driven dev folder structure

### ISSUE THREAD

**Issue by jesstracy** [jesstracy/gapi#4]

**Comment by chrisevett** [comment]
@jesstracy take a look at this and see what you think. This is the reorganization from this issue plus it adds gorm. Dont try to test it because it doesnt work, just wanna see if you agree with the direction I'm going in

https://github.com/chrisevett/gapi/commit/09c82e2e74fdf9b68406514c9e4b7bc5666b003f

**Comment by jesstracy** [comment]
@chrisevett YES I agree with the direction you are going in. :) looks awesome. can we merge it in? I was having trouble figuring out how to pass stuff around without moving all my functions into the same app.go file (like routes and handler methods and all that). so this is great.

**Comment by chrisevett** [comment]
I'll merge it in once i get the database working
